name: Warframe General Discussion Topics
on:
  rss:
    url: https://forums.warframe.com/discover/837.xml
    config:
      limit: 15
      force: false
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RSS1TESTCHANNEL }}
          token: ${{ secrets.TELEGRAM_GENSHIN_TOKEN }}
          format: markdown
          message: |
            *New Reply from [DE]Megan*

            *${{ on.rss.outputs.title }}*
            ${{ on.rss.outputs.link }}
