name: Warframe General Discussion Topics
on:
  rss:
    url: http://feeds.feedburner.com/WFGeneralDiscussion
    config:
      limit: 15
      force: false
jobs:
  telegram:
    name: Warframe General Discussion Topics Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Warframe General Discussion Topics Send a telegram message 1
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_WFGENERALDISCUSSION_CHANNEL }}
          token: ${{ secrets.TELEGRAM_WARFRAMENEWSBOT_TOKEN }}
          format: markdown
          message: |
            *${{ on.rss.outputs.title }}*

            ${{ on.rss.outputs.link }}
