name: Warframe General Discussion
on:
  rss:
    url: https://forums.warframe.com/forum/36-general-discussion.xml
    config:
      limit: 15
      force: true
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_RSS1TESTCHANNEL }}
          token: ${{ secrets.TELEGRAM_GENSHIN_TOKEN }}
          format: markdown
          message: |
            <b>${{ on.rss.outputs.title }}</b>
            ${{ on.rss.outputs.description }}

            ${{ on.rss.outputs.link }}
