name: Warframe Dev Workshops
on:
  rss:
    url: https://forums.warframe.com/forum/123-developer-workshop-update-notes.xml
    config:
      limit: 15
      force: false
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_WFNEWS_CHANNEL }}
          token: ${{ secrets.TELEGRAM_WARFRAMENEWSBOT_TOKEN }}
          format: markdown
          message: |
            *Developer Workshop & Update Notes*

            *${{ on.rss.outputs.title }}*
            ${{ on.rss.outputs.link }}
